[profile.default]
solc = '0.8.27'
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@era-l1-contracts/=lib/v2-testnet-contracts/l1/contracts/",
    "@era-l2-contracts/=lib/v2-testnet-contracts/l2/contracts/",
    "@era-system-contracts/=lib/v2-testnet-contracts/l2/system-contracts/",
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
]

fs_permissions = [
    { access = "read", path = "./zkout/Account.sol/Account.json" },
    { access = "read", path = "./zkout/AAFactory.sol/AAFactory.json" },
]

[rpc_endpoints]
zksync = "${ZKSYNC_NODE_RPC_URL}"
zksync_sepolia = "${ZKSYNC_SEPOLIA_NODE_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
